name: release
on:
  release:
    types: [published]
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
      PKG_FOLDER:  .${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
    steps:
    
      - name: download-source
        run: curl -sL "${{ github.event.release.tarball_url }}" >"$ARCHIVE_NAME".tar.gz
        
      - name: unzip-source
        run: mkdir "$PKG_FOLDER" && tar -xzf "$ARCHIVE_NAME".tar.gz -C "$PKG_FOLDER" --strip-components 1
        
      - name: clean-source
        run: |
          rm -rf "$PKG_FOLDER"/{.github,assets}
          mkdir Module64
          mkdir Module32
          mkdir Work64
          mkdir Work32
          
      - name: fetch-data
        run: |
          cd Work64
          curl  https://qemu.weilnetz.de/w64/ --output page.txt
          cat page.txt
          cd ..
          cd Work32
          curl  https://qemu.weilnetz.de/w32/ --output page.txt
          cat page.txt
          cd ..
          tree
        
      - name: parse-data
        run: |
          cd Work64
          grep -o ">qemu-w64-setup-.*exe" page.txt | cut -c 2- > grep.txt
          echo Found URL: https://qemu.weilnetz.de/w64/"$(cat grep.txt)"
          ls * -r
          cd ..
          cd Work32
          grep -o ">qemu-w32-setup-.*exe" page.txt | cut -c 2- > grep.txt
          echo Found URL: https://qemu.weilnetz.de/w32/"$(cat grep.txt)"
          ls * -r
          cd ..
       
      - name: download-data
        run: |
          cd Work64
          echo Download URL: https://qemu.weilnetz.de/w64/"$(cat grep.txt)"
          curl https://qemu.weilnetz.de/w64/"$(cat grep.txt)" --output qemu-w64.exe
          cd ..
          cd Work32
          echo Download URL: https://qemu.weilnetz.de/w32/"$(cat grep.txt)"
          curl https://qemu.weilnetz.de/w64/"$(cat grep.txt)" --output qemu-w32.exe
          cd ..   
        
      - name: extract-data
        id: extract-data
        uses: edgarrc/action-7z@v1
        run: |
          7z x Work64/qemu-w64.exe -oModule64/
          7z x Work32/qemu-w32.exe -oModule32/
 
      - name: clean-module
        run: |
          sudo chmod -R o+rwx Module64/
          cd Module64/
          echo remove files
          sudo rm -rf *PLUGINSDIR/
          echo remove done
          ls * -r
          cd ..
          
      - name: copy-module-next
        run: |
          cp -r Module64/. "$PKG_FOLDER"/
          cd "$PKG_FOLDER"/
          sudo rm -rf README.md
          echo Final Package files
          ls *
          cd ..
          echo Root
          ls *
          
      - name: package-info
        run: |
          echo "auto generate package" > package.info
          cat package.info
        
      - name: create-archive
        run: |
          tar -cvf "$ARCHIVE_NAME".tar "$PKG_FOLDER"
          sha256sum "$ARCHIVE_NAME".tar > .checksum
          tar rf "$ARCHIVE_NAME".tar package.info .checksum
      - name: compress-archive
        run: |
         sudo rm "$ARCHIVE_NAME".tar.gz
         gzip "$ARCHIVE_NAME".tar
          
      - name: create-checksum
        id: create-checksum
        run: |
          sha256sum "$ARCHIVE_NAME".tar.gz >checksum.txt
          echo "checksum = $(cut -d ' ' -f 1 checksum.txt)"  >> $GITHUB_OUTPUT
          
      - name: upload-archive
        id: upload-archive
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}.tar.gz
          asset_name: ${{ env.ARCHIVE_NAME }}.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: upload-checksum
        id: upload-checksum
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: checksum.txt
          asset_name: checksum.txt
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: trigger-formula-upgrade
        run: |
          curl -s -X POST \
            https://api.github.com/repos/wkTls/module/dispatches \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{
                "event_type": "upgrade-formula",
                "client_payload": {
                  "formula": "k1s",
                  "url": "${{ steps.upload-archive.outputs.browser_download_url }}",
                  "sha256": "${{ steps.create-checksum.outputs.checksum }}"
                }
              }'
            
      - if: failure() 
        name: rollback-release(delete tag/id)
        run: |
          curl -s -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.event.repository.full_name }}/releases/${{ github.event.release.id }}
          curl -s -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.event.repository.full_name }}/git/refs/tags/${{ github.event.release.tag_name }}