name: release
on:
  release:
    types: [published]
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
    steps:
      - name: download-source
        run: curl -sL "${{ github.event.release.tarball_url }}" >"$ARCHIVE_NAME".tar.gz
      - name: unzip-source
        run: mkdir "$ARCHIVE_NAME" && tar -xzf "$ARCHIVE_NAME".tar.gz -C "$ARCHIVE_NAME" --strip-components 1
      - name: clean-source
        run: rm -rf "$ARCHIVE_NAME"/{.github,assets}
      - name: download-data
        run: |
          mkdir Module
          mkdir Qemu
          cd Qemu
          curl  https://qemu.weilnetz.de/w64/
          curl  https://qemu.weilnetz.de/w64/ --output page.txt
          ls * -r
          cat page.txt
          cd ..
          tree
          ls * -r
        
      - name: download-next
        run: |
          ls * -r
          cd Qemu
          ls * -r
          grep -o ">qemu-w64-setup-.*exe" page.txt | cut -c 2- > grep.txt
          echo Found URL: https://qemu.weilnetz.de/w64/"$(cat grep.txt)"
          curl https://qemu.weilnetz.de/w64/"$(cat grep.txt)" --output qemu-w64.exe
          cd ..
        
      - name: extract-qemu
        id: extract-qemu
        uses: edgarrc/action-7z@v1
        with:
          args: 7z x Qemu/qemu-w64.exe -oModule/
 
      - name: clean-module
        run: |
          sudo chmod -R o+rwx Module/
          cd Module/
          echo remove files
          sudo rm -rf --no-preserve-root *PLUGINSDIR/
          echo remove done
          ls * -r
          cd ..
      - name: copy-module-next
        run: |
          cp -r Module/. "$ARCHIVE_NAME"/
          cd "$ARCHIVE_NAME"/
          sudo rm -rf README.md
          echo Final Package files
          cd ..
          tree
      - name: create-archive
        run: |
          tar -czf "$ARCHIVE_NAME".tar.gz "$ARCHIVE_NAME"
      - name: create-checksum
        id: create-checksum
        run: |
          sha256sum "$ARCHIVE_NAME".tar.gz >checksum.txt
          echo "checksum = $(cut -d ' ' -f 1 checksum.txt)"  >> $GITHUB_OUTPUT
      - name: upload-archive
        id: upload-archive
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ env.ARCHIVE_NAME }}.tar.gz
          asset_name: ${{ env.ARCHIVE_NAME }}.tar.gz
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload-checksum
        id: upload-checksum
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: checksum.txt
          asset_name: checksum.txt
          asset_content_type: text/plain
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: trigger-formula-upgrade
        run: |
          curl -s -X POST \
            https://api.github.com/repos/wkTls/module/dispatches \
            -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '
              {
                "event_type": "upgrade-formula",
                "client_payload": {
                  "formula": "k1s",
                  "url": "${{ steps.upload-archive.outputs.browser_download_url }}",
                  "sha256": "${{ steps.create-checksum.outputs.checksum }}"
                }
              }
            '
      - if: failure() 
        name: abort
        run: |
          curl -s -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.event.repository.full_name }}/releases/${{ github.event.release.id }}
          curl -s -X DELETE \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.event.repository.full_name }}/git/refs/tags/${{ github.event.release.tag_name }}